name: Cypress E2E Pipeline

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependencias
        run: npm install

      - name: Rodar Testes em Background
        run: npx cypress run